# Generated by Django 2.2.5 on 2019-09-15 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dname', models.CharField(max_length=200)),
                ('dpass', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Complaints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cdept', models.CharField(max_length=200)),
                ('cquery', models.CharField(max_length=500)),
                ('cassignee', models.CharField(max_length=200)),
                ('cstatus', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=200)),
                ('smail', models.EmailField(max_length=200)),
                ('spass', models.CharField(max_length=200)),
            ],
        ),
    ]
