# Generated by Django 2.2.5 on 2019-09-15 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cogp', '0002_remove_student_sname'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaints',
            name='cuser',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='complaints',
            name='cassignee',
            field=models.CharField(default='', max_length=200),
        ),
    ]
