# Generated by Django 2.2.5 on 2019-09-15 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cogp', '0003_auto_20190915_1352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaints',
            name='cuser',
        ),
        migrations.AlterField(
            model_name='complaints',
            name='cstatus',
            field=models.CharField(default='Unresolved', max_length=200),
        ),
    ]
